# Generated by Django 4.2.28 on 2026-04-25 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitinterview',
            name='overall_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Rating 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
