# Generated by Django 4.2.28 on 2026-04-25 10:59

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employees/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp']), apps.core.validators.FileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employees/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg']), apps.core.validators.FileSizeValidator(10)]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'employee_id')},
        ),
    ]
